# Generated by Django 4.2.11 on 2024-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('tax_region_name', models.CharField(max_length=100, verbose_name='Tax Region Name')),
                ('estimated_combined_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Estimated Combined Rate')),
                ('state_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='State Rate')),
                ('estimated_county_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Estimated County Rate')),
                ('estimated_city_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Estimated City Rate')),
                ('estimated_special_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Estimated Special Rate')),
                ('risk_level', models.IntegerField(verbose_name='Risk Level')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rate',
                'ordering': ('state', 'tax_region_name', 'zipcode'),
                'unique_together': {('state', 'zipcode', 'tax_region_name')},
            },
        ),
    ]
